### PR TITLE
added .query_raw(), .index(), .mget(), fixed missing import, always POST on query/query_raw

### PR DESCRIPTION
**Pull request by ddorian**

### CODE REVIEW

**Comment by nickvasilyev** [comment]
Thanks, I am running some tests and it is failing in the requests module. It looks like auth  = (None, None) evaluates to true for some reason which then gets passed on to requests that craps out when it sees that. I don't think this has been changed recently, so I am not sure what is going on.

**Comment by nickvasilyev** [comment]
I am running into an issue with unit tests passing. I've created a new dev branch, lets use that branch for active development. I will merge back to master once everything is passing.

**Comment by ddorian** [comment]
Can you post your test log ?

**Comment by ddorian** [comment]
Mine is:
```
 ('N/A', "HTTPConnectionPool(host='localhost', port=963): Max retries exceeded with url: /solr/SolrClient_unittest/schema/fields?wt=json&indent=false (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7056795b70>: Failed to establish a new connection: [Errno 111] Connection refused',))", ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost', port=963): Max retries exceeded with url: /solr/SolrClient_unittest/schema/fields?wt=json&indent=false (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f7056795b70>: Failed to establish a new connection: [Errno 111] Connection refused',))",),))
```
For some reason solr is refusing the connection. Maybe solr has a connection limit or soemthing..

**Comment by nickvasilyev** [comment]
I have the other issues figured out, will commit them a bit later.

This connection refused error is most likely because Solr 6.3 is not in Vagrant config, so it doesn't get installed. There are a few files that need to be edited to get the new version to work and have to make a sample config (schema, solrconfig). There are some notes in that repo and in SolrClient test readme on, you can try to take a stab at it, otherwise I can do it tonight. I want to remove some of the older versions that I am not working on from the list as well and trim the fat on that VM.

**Comment by ddorian** [comment]
I will leave that to you since you have experience on it.
I'm working on the smart routing that I mentioned on the other issue. Hopefully after that we'll have a new release ?

**Pull request merged**
