### PR TITLE
move host-selection to separate class, add PlainRouter(), RandomRouter(), added collections.cluster_status_raw()

### PR DESCRIPTION
**Pull request by ddorian**
actually, this is just 'plain' routing, the smart one will be in another pull request

### CODE REVIEW

**Comment by nickvasilyev** [comment]
Please include some tests for this.

**Comment by ddorian** [comment]
But it functions exactly the same, just moved the functions to a new class.

Any example test ?

**Comment by nickvasilyev** [comment]
Well you want to make sure that the requests are actually getting shuffled. Also, once concern I have with this if there is a large number of hosts is the creep of file descriptors and TIME_WAIT network sockets. Generally, requests.Session will take care of this because it will re-use the sockets, however I don't know how it will work if there is a shuffle for every outgoing query and you have a lot of nodes.

**Comment by ddorian** [comment]
How to test that they're getting shuffeled (since it's 1 function call)? 
Check that they're not the same after shuffling ?

Note that by default it works as before. 
1 case when random-hosts may be good is when using 'query nodes'. Query nodes don't keep data but just forward/join queries from 'data nodes' (so they'll have big cpu, slow disk, medium memory). Though I don't know if they exist in solr (they do in elasticsearch). In that case, it may mean you'll have 1/10 query-nodes compared to data nodes, and connect only to them from the client. Makes sense ?

**Comment by nickvasilyev** [comment]
Thanks, that is interesting, I re-ran everything from scratch and it was working fine for the most part. I had to make a schema change for 6.3.0 to get test_reindexer to work. Other then that, everything was fine. 

I merged the last pull request as well, thanks for the contribution. If you are still working on this and want to include it in the code, please send an updated PR to the dev branch.

Thanks

**Comment by ddorian** [comment]
Merged with dev.

**Comment by nickvasilyev** [comment]
Merged into dev branch. Thanks. I am going to make a few changes before merging it into master:
 - Take it out of SolrClient and put it in TransportBase
 - Add unit tests to make sure routing is properly happening
 - Update Documentation

Feel free to jump on any of those if you want to.

**Pull request merged**
