### PR TITLE
shuffle hosts on TransportBase

### PR DESCRIPTION
**Pull request by ddorian**
makes sense ?

### CODE REVIEW

**Comment by nickvasilyev** [comment]
Thanks for the pull requests. SolrCloud already load balances all requests internally, so if you query a single host, the response may actually be generated from shards on other replicas. In Solr classic, you will probably want to primarily query the replica since it is not doing the indexing and only getting updated from the master.

**Comment by ddorian** [comment]
1.
Imagine you have 4 servers * 20 processes. Each doing queries, all hitting 1 node. (since we all have the same configuration on all nodes, meaning the same sorted list of hosts).
That will increase cpu usage on that first node, right (even just being a proxy)?

2. Imagine the first node is down. Now ALL requests (from all processes) take a little longer, because they can't reach the first one.

**Comment by ddorian** [comment]
I think my reasons make sense in cluster-mode ?
Or maybe we can have different configs for classic/cloud ?

**Comment by nickvasilyev** [comment]
Sure, I am running unit tests on these two pull requests now. Will include as soon as everything passes.

**Pull request merged**
