### PR TITLE
Fancy router

### PR DESCRIPTION
**Pull request by ddorian**
mmh3 fails to build/compile.

Can you fix the vm (by installing apt-get install python-dev) and I finish the tests after ?

### CODE REVIEW

**Comment by nickvasilyev** [comment]
Done, check it out. I haven't checked it out yet, but please make sure that the new dependency doesn't prevent the usage of the entire library if it is not present. For example, kazoo is only required if you are using the ZK module. If it is not installed, it will not crap out on the start so you can still do basic querying / indexing, etc...

**Comment by ddorian** [comment]
Yeah I've done it that way. Though I need fixed the vm so it builds mmh3 when running the tests to finish the tests

**Comment by nickvasilyev** [comment]
I added python-dev to apt install list.

**Comment by ddorian** [comment]
I can install it manually (after installing python-dev) doing `sudo pip install mmh3` but on run_tests.py it's still can't be built (havent tried yet with your changes)

**Comment by ddorian** [comment]
Sorry, you also need to add `sudo apt-get install python3.5-dev` and then it compiles.

**Pull request merged**
