### PR TITLE
raise last-exception instead of returning None after failing to conta…

### PR DESCRIPTION
**Pull request by ddorian**
…ct all hosts

### CODE REVIEW

**Comment by ddorian** [comment]
Any thing else I should do to get these pull requests merged ?

**Comment by nickvasilyev** [comment]
Add unit tests to make sure it's working, I mean without them, how can you be certain that it is working exactly as you want it to? Since your changes are pretty much localized to transport, I would just say to add a new test_transport test. 

send_request in transport base returns a bit of extra information about the request that goes out. I suggest you write tests directly against that class. You can make a new SolrClient and then just hit transport through solr.transport.send_request or something like that.

**Comment by ddorian** [comment]
About send_request i think it's broken currently. because if the host(s) is/are down(like when i tested for 6.3 that wasnt installed in the vm), you don't get the original exception, but it returns None, which then can't be unpacked by response,info = None (so you get can't unpack None, which doesn't make sense)

so the only thing that I can test here(which i'm gonna write), is that if I send a request and it fails, then we get an exception, and not None (which fails unpacking) 

while the other commit is just using 1 log command instead of 2 because so test there ?

**Comment by nickvasilyev** [comment]
Yea, the logging is fine, I am not too worried about that, just the other stuff. 

I updated Vagrant box and fixed a few things in this repo as well. The vagant box now brings up Solr 6.3 and this repo has the required schema for the tests as well. Can you take it for a whirl and let me know if you run into any issues?

**Comment by ddorian** [comment]
I got this error when trying to spin a new box:
```
TASK [Create source_coll Collection] *******************************************
changed: [default]

TASK [Upload source_coll schema] ***********************************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "/opt/solrs/6.3.0/solr-6.3.0/server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:8001/solr-6.3.0 -cmd upconfig -confname source_coll -confdir /vagrant/code/test/resources/6.3.0/", "delta": "0:00:00.909105", "end": "2016-12-20 11:22:39.113734", "failed": true, "rc": 1, "start": "2016-12-20 11:22:38.204629", "stderr": "Exception in thread \"main\" java.io.IOException: Path /vagrant/code/test/resources/6.3.0 does not exist\n\tat org.apache.solr.common.cloud.ZkMaintenanceUtils.uploadToZK(ZkMaintenanceUtils.java:234)\n\tat org.apache.solr.common.cloud.SolrZkClient.uploadToZK(SolrZkClient.java:803)\n\tat org.apache.solr.common.cloud.ZkConfigManager.uploadConfigDir(ZkConfigManager.java:78)\n\tat org.apache.solr.cloud.ZkCLI.main(ZkCLI.java:227)", "stdout": "", "stdout_lines": [], "warnings": []}
        to retry, use: --limit @/vagrant/ansible/plays/playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=114  changed=100  unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

**Comment by nickvasilyev** [comment]
For the first error, make sure you are pointing to the latest branch of SolrClient, it has the collection configs for 6.3, it looks like the code that you pulled down didn't have it. 

I'll have to change the playbooks for the second error to ignore failure in that case.

**Comment by ddorian** [comment]
By 'pointing', you mean on `VagrantFile` ? If yes, I left it as default. I confirm I had the latest master and the issue is still there.

**Comment by nickvasilyev** [comment]
Sorry for the delay man, been slammed. The Solr configs are still in the SolrClient repo,  you will need to make sure that the branch that Vagrantfile is pointing to has the configs for 6.3.0.

**Comment by ddorian** [comment]
I literally started from scratch and I still get the error. Am I missing any new command compared to the old way ?

```
guru@guru:~/Desktop/empty$ git clone https://github.com/moonlitesolutions/SolrVagrant.git
Cloning into 'SolrVagrant'...
remote: Counting objects: 147, done.
remote: Total 147 (delta 0), reused 0 (delta 0), pack-reused 147
Receiving objects: 100% (147/147), 21.17 MiB | 629.00 KiB/s, done.
Resolving deltas: 100% (55/55), done.
Checking connectivity... done.
guru@guru:~/Desktop/empty$ ls
SolrVagrant
guru@guru:~/Desktop/empty$ cd SolrVagrant
guru@guru:~/Desktop/empty/SolrVagrant$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: SolrVagrant_default_1482818174121_6639
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 9521 (guest) => 9521 (host) (adapter 1)
    default: 9553 (guest) => 9553 (host) (adapter 1)
    default: 9621 (guest) => 9621 (host) (adapter 1)
    default: 9630 (guest) => 9630 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/guru/Desktop/empty/SolrVagrant
==> default: Running provisioner: ansible_local...
    default: Installing Ansible...
    default: Running ansible-playbook...
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and 
make sure become_method is 'sudo' (default).
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

PLAY [Base Software Installation] **********************************************

TASK [setup] *******************************************************************
ok: [default]

TASK [Add Open JDK Repository] *************************************************
changed: [default]

TASK [Add Repository For Pythons :)] *******************************************
changed: [default]

TASK [Update Apt] **************************************************************
changed: [default]

TASK [Install Base Packages] ***************************************************
changed: [default] => (item=[u'python3', u'python3-pip', u'openjdk-8-jdk', u'git', u'nginx', u'python-virtualenv', u'ansible', u'unzip', u'python-tox', u'python3.3', u'python3.4', u'python3.5'])

TASK [Increase File Descriptors] ***********************************************
changed: [default]

TASK [Increase File Descriptors] ***********************************************
changed: [default]

TASK [Download Code] ***********************************************************
changed: [default]

TASK [Install Python Reqs] *****************************************************
changed: [default]

TASK [Update perms] ************************************************************
changed: [default]

TASK [Create App Dir] **********************************************************
changed: [default]

TASK [Change Opt Permissions] **************************************************
changed: [default]

TASK [Create Startup File] *****************************************************
changed: [default]

TASK [Startup Service jerry-rig] ***********************************************
changed: [default]

PLAY [Deploy ZK] ***************************************************************

TASK [setup] *******************************************************************
ok: [default]

TASK [Crate App Dir] ***********************************************************
changed: [default]

TASK [Crate Data Dir] **********************************************************
changed: [default]

TASK [Deploy App] **************************************************************
changed: [default]

TASK [Deploy Config] ***********************************************************
changed: [default]

TASK [Create IDs] **************************************************************
changed: [default]

TASK [Change Perm ZKServer] ****************************************************
changed: [default]

TASK [Change Perm ZKServer] ****************************************************
changed: [default]

TASK [Start] *******************************************************************
changed: [default]

TASK [wait_for] ****************************************************************
ok: [default]

TASK [Startup Service jerry-rig] ***********************************************
changed: [default]

TASK [Crate App Dir] ***********************************************************
changed: [default]

TASK [Crate Data Dir] **********************************************************
changed: [default]

TASK [Deploy App] **************************************************************
changed: [default]

TASK [Deploy Config] ***********************************************************
changed: [default]

TASK [Create IDs] **************************************************************
changed: [default]

TASK [Change Perm ZKServer] ****************************************************
changed: [default]

TASK [Change Perm ZKServer] ****************************************************
changed: [default]

TASK [Start] *******************************************************************
changed: [default]

TASK [wait_for] ****************************************************************
ok: [default]

TASK [Startup Service jerry-rig] ***********************************************
changed: [default]

TASK [Crate App Dir] ***********************************************************
changed: [default]

TASK [Crate Data Dir] **********************************************************
changed: [default]

TASK [Deploy App] **************************************************************
changed: [default]

TASK [Deploy Config] ***********************************************************
changed: [default]

TASK [Create IDs] **************************************************************
changed: [default]

TASK [Change Perm ZKServer] ****************************************************
changed: [default]

TASK [Change Perm ZKServer] ****************************************************
changed: [default]

TASK [Start] *******************************************************************
changed: [default]

TASK [wait_for] ****************************************************************
ok: [default]

TASK [Startup Service jerry-rig] ***********************************************
changed: [default]

PLAY [Deploy Solr] *************************************************************

TASK [setup] *******************************************************************
ok: [default]

TASK [Deploying Solr] **********************************************************
included: /vagrant/ansible/roles/solr/tasks/deploy.yml for default
included: /vagrant/ansible/roles/solr/tasks/deploy.yml for default
included: /vagrant/ansible/roles/solr/tasks/deploy.yml for default
included: /vagrant/ansible/roles/solr/tasks/deploy.yml for default

TASK [Create App Dir] **********************************************************
changed: [default]

TASK [Copy Solr Tar] ***********************************************************
changed: [default]

TASK [Updating Configs] ********************************************************
changed: [default]

TASK [Create ZK Chroot] ********************************************************
changed: [default]

TASK [Starting Solr] ***********************************************************
changed: [default]

TASK [Waiting for Solr to Start] ***********************************************
ok: [default]

TASK [Upload basic config] *****************************************************
changed: [default]

TASK [Upload data_driven_schema_configs] ***************************************
changed: [default]

TASK [Create SolrClient_unittest Collection] ***********************************
changed: [default]

TASK [Create source_coll Collection] *******************************************
changed: [default]

TASK [Upload source_coll schema] ***********************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]
 [WARNING]: Consider using get_url or uri module rather than running curl


TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Create dest_coll Collection] *********************************************
changed: [default]

TASK [Upload dest_coll schema] *************************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Startup Service jerry-rig] ***********************************************
changed: [default]

TASK [Create App Dir] **********************************************************
changed: [default]

TASK [Copy Solr Tar] ***********************************************************
changed: [default]

TASK [Updating Configs] ********************************************************
changed: [default]

TASK [Create ZK Chroot] ********************************************************
changed: [default]

TASK [Starting Solr] ***********************************************************
changed: [default]

TASK [Waiting for Solr to Start] ***********************************************
ok: [default]

TASK [Upload basic config] *****************************************************
changed: [default]

TASK [Upload data_driven_schema_configs] ***************************************
changed: [default]

TASK [Create SolrClient_unittest Collection] ***********************************
changed: [default]

TASK [Create source_coll Collection] *******************************************
changed: [default]

TASK [Upload source_coll schema] ***********************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Create dest_coll Collection] *********************************************
changed: [default]

TASK [Upload dest_coll schema] *************************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Startup Service jerry-rig] ***********************************************
changed: [default]

TASK [Create App Dir] **********************************************************
changed: [default]

TASK [Copy Solr Tar] ***********************************************************
changed: [default]

TASK [Updating Configs] ********************************************************
changed: [default]

TASK [Create ZK Chroot] ********************************************************
changed: [default]

TASK [Starting Solr] ***********************************************************
changed: [default]

TASK [Waiting for Solr to Start] ***********************************************
ok: [default]

TASK [Upload basic config] *****************************************************
changed: [default]

TASK [Upload data_driven_schema_configs] ***************************************
changed: [default]

TASK [Create SolrClient_unittest Collection] ***********************************
changed: [default]

TASK [Create source_coll Collection] *******************************************
changed: [default]

TASK [Upload source_coll schema] ***********************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Create dest_coll Collection] *********************************************
changed: [default]

TASK [Upload dest_coll schema] *************************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Reload Collection] *******************************************************
changed: [default]

TASK [Startup Service jerry-rig] ***********************************************
changed: [default]

TASK [Create App Dir] **********************************************************
changed: [default]

TASK [Copy Solr Tar] ***********************************************************
changed: [default]

TASK [Updating Configs] ********************************************************
changed: [default]

TASK [Create ZK Chroot] ********************************************************
changed: [default]

TASK [Starting Solr] ***********************************************************
changed: [default]

TASK [Waiting for Solr to Start] ***********************************************
ok: [default]

TASK [Upload basic config] *****************************************************
changed: [default]

TASK [Upload data_driven_schema_configs] ***************************************
changed: [default]

TASK [Create SolrClient_unittest Collection] ***********************************
changed: [default]

TASK [Create source_coll Collection] *******************************************
changed: [default]

TASK [Upload source_coll schema] ***********************************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "/opt/solrs/6.3.0/solr-6.3.0/server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:8001/solr-6.3.0 -cmd upconfig -confname source_coll -confdir /vagrant/code/test/resources/6.3.0/", "delta": "0:00:01.040082", "end": "2016-12-27 06:50:36.260773", "failed": true, "rc": 1, "start": "2016-12-27 06:50:35.220691", "stderr": "Exception in thread \"main\" java.io.IOException: Path /vagrant/code/test/resources/6.3.0 does not exist\n\tat org.apache.solr.common.cloud.ZkMaintenanceUtils.uploadToZK(ZkMaintenanceUtils.java:234)\n\tat org.apache.solr.common.cloud.SolrZkClient.uploadToZK(SolrZkClient.java:803)\n\tat org.apache.solr.common.cloud.ZkConfigManager.uploadConfigDir(ZkConfigManager.java:78)\n\tat org.apache.solr.cloud.ZkCLI.main(ZkCLI.java:227)", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/vagrant/ansible/plays/playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=114  changed=100  unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by nickvasilyev** [comment]
This is what it is missing:

https://github.com/moonlitesolutions/SolrClient/tree/master/test/resources/6.3.0

Make sure that the version of SolrClient you are pulling down in your vagrant file has that in there.

**Comment by ddorian** [comment]
Still error after pasting that:

```

TASK [Run Tests] ***************************************************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "/vagrant/code/run_tests.py >> /vagrant/code/TEST_RESULTS.log", "delta": "0:00:00.326204", "end": "2016-12-30 15:48:38.103888", "failed": true, "rc": 1, "start": "2016-12-30 15:48:37.777684", "stderr": "ERROR: toxini file 'tox.ini' not found\nTraceback (most recent call last):\n  File \"/vagrant/code/run_tests.py\", line 37, in <module>\n    REPORT[ver][solr][test] = subprocess.call([python, \"-m\", \"unittest\", \"test.{}\".format(test)])\n  File \"/usr/lib/python3.4/subprocess.py\", line 537, in call\n    with Popen(*popenargs, **kwargs) as p:\n  File \"/usr/lib/python3.4/subprocess.py\", line 859, in __init__\n    restore_signals, start_new_session)\n  File \"/usr/lib/python3.4/subprocess.py\", line 1457, in _execute_child\n    raise child_exception_type(errno_num, err_msg)\nFileNotFoundError: [Errno 2] No such file or directory: '.tox/py33/bin/python3.3'", "stdout": "", "stdout_lines": [], "warnings": []}
        to retry, use: --limit @/vagrant/ansible/plays/playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=124  changed=108  unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by nickvasilyev** [comment]
That last command runs the tests for you, you can just re-run them manually. I do this so it does everything for me and I can let it run overnight or something like that.

**Comment by ddorian** [comment]
Still doesn't work (only 6.3.0, just can't find solr from client) while 6.2.1 works

**Comment by nickvasilyev** [comment]
That's strange man. Can you try to just run a fresh pull from SolrVagrant and point it to the latest branch of SolrClient and see it gets any

**Comment by ddorian** [comment]
..  why close this ? I will create the test and then merge and then close ?

**Comment by nickvasilyev** [comment]
Sorry, closed it by mistake. I am re-running through all the tests using the master branch of SolrClient and SolrVagrant. Should finish in a few hours, I will check out if I run into any problems. Thanks for all the contributions too man, sorry you are running into so many issues.

**Comment by ddorian** [comment]
Actually I fixed it (after copying schema inside /code/, and recreating vagrant). 
Also added test. Merge if it's enough?

**Pull request merged**
